Chakosh\NewsBundle\Entity\postCategory:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
    manyToMany:
      posts:
        targetEntity: Post
        inversedBy: postCategory
        joinTable:
          name: post_category
          joinColumns:
            postCategory_id:
              referencedColumnName: id
          inverseJoinColumns:
            post_id:
              referencedColumnName: id              
              nullable: false             
    lifecycleCallbacks: {  }
