parameters:
#    chakosh_search.example.class: Chakosh\SearchBundle\Example

services:
#    chakosh_search.example:
#        class: %chakosh_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
