parameters:
#    chakosh_blog.example.class: Chakosh\BlogBundle\Example

services:
#    chakosh_blog.example:
#        class: %chakosh_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
