Chakosh\BlogBundle\Entity\Book:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
        author:
            - NotBlank: ~
            - Length:
                min: 1
                max: 255
        #cover:
            #- Url: ~
        #file:
            #- Url: ~        
            
        