0chakosh_options:
    resource: "@ChakoshOptionsBundle/Resources/config/routing.yml"
    prefix:   /

chakosh_search:
    resource: "@ChakoshSearchBundle/Resources/config/routing.yml"
    prefix:   /

chakosh_comment:
    resource: "@ChakoshCommentBundle/Resources/config/routing.yml"
    prefix:   /

chakosh_news:
    resource: "@ChakoshNewsBundle/Resources/config/routing.yml"
    prefix:   /

chakosh_upload:
    resource: "@ChakoshUploadBundle/Resources/config/routing.yml"
    prefix:   /

chakosh_home:
    resource: "@ChakoshHomeBundle/Resources/config/routing.yml"
    prefix:   /

chakosh_security:
    resource: "@ChakoshSecurityBundle/Resources/config/routing.yml"
    prefix:   /
    #schemes: [https]

chakosh_blog:
    resource: "@ChakoshBlogBundle/Resources/config/routing.yml"
    prefix:   /
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile   

# _imagine:
#     resource: .
#     type:     imagine