parameters:
#    chakosh_comment.example.class: Chakosh\CommentBundle\Example

services:
#    chakosh_comment.example:
#        class: %chakosh_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
